apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: go-web-home
build:
  artifacts:
    - image: hongsgo/go-web-home
deploy:
  kubectl:
    manifests:
      - k8s/go-web-home.deploy.yaml
      - k8s/go-web-home.svc.yaml
