apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: go-web-home
build:
  local:
    push: true
  artifacts:
    - image: hongsgo/gowebhome
deploy:
  kubectl:
    manifests:
      - k8s/go-web-home.deploy.yaml
      - k8s/go-web-home.svc.yaml
