apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: gowebhome
  name: gowebhome
  selfLink: /apis/apps/v1/namespaces/default/deployments/gowebhome
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: gowebhome
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: gowebhome
    spec:
      containers:
        - image: hongsgo/gowebhome
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 1323
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 1323
            initialDelaySeconds: 3
            periodSeconds: 3
          name: gowebhome
          ports:
            - containerPort: 1323
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
